sudo: false

services:
  - docker
  
env:
  global:
  - secure: "YEssttXkPhcgn/5uC8VmWPd96nFy0Ke3w8YzwoRTcEUpFsx2GtK9NAC90w1+h/LyGOBQo2QhV8Ao9uivYkXK5NhAUaiHIXAsrEO1nhTwsl0rHM9NjkVI8KjhqAY72BtQEoAPqb01I8mwvl9PYW4fNzU9M4k/rX+Sc6a/V68DNHiISkWafXyS6xcKlurbCMuBbdVjOc63vgCOrNG8e84HvSGb6L/8ovTTdl4qMrWFdEZ+Pd9sg0lzIpvSYyoLfmdo4NoJXk6mhHCtFKDDHJkUdZzNdhCgfEO731Ii3OpRhtkdjfHthDu+V+fCFKIzbxsQyh979JRLY4yGdDaftoju1E4r2/A2CMO3I744WqEPYhMcYcbX5iVotn3TjGDFNGpdptu5X2BLXBvbW0/De/gY67Pb0tsjb6wWhbZjVttB9h8Sa7COx9cT8AUie08C24sK462Yk9FHo6X3gVNqn0tnIVtU1RDhDoFhUkljkRJq/S/DXxeZ/pBcgVz3En7zvwMJxydHLjPHSpl3GiBs4xT3KpAjg9XdudjkuKnx+OBm2hbRPM6XX8bcwcYZtsG46lp5Qpy9f0UcnB12xFDxgs5miJnF/7/UEia9cA0d7Rt7e3FNRcVFHINOGVYcwCsUC14dVmD2gNxOhZptgh5zbTmueVF11VhXt7RioWis/l3y9ZE="
  - secure: "YfSrWvyqRALkghXx4y+rGGkpLpGyeQPz4/1soErO0YceiCDwokcqAyyWR+xcIEoQBeBG+LHK/1/FK5lHv1MRc/3j2mu8fQ189xV1UOBorSo3tSP4e1PO1GwnfOXksnh+Lz/8ozYmnYe9oiFyurq17J6eVDkeno6/oUD2TYbiGrlg57eqhd/U6LuJw5cXryTOrrjymkCQX1ooQKFNzNu0f/rUTu+y71z8lLYqmMRuA33S5Fjsq9r4ouCdIeTbpAPh3Xl++TCy8phAYYvcXgvgh+nK8khlS5tXkCWbNtnRVZccQOq3enPjQ3i+8otsSfGePoUWnBV+LSgSAI2msoDdrtNwZ6TSg/UyQEB4B76ENmStK1cnT3d2+N2d8ILkZ+eiwhv/lDCWXrB8h5Cm6DDDap36TLKVeJBPfxzq+FFdwODfBtP8spT7OVmqJcVXtpHa2DS3qtYCCQjySGTulrWmHtUvPfl647afSwW9b1MbAi0wzOQbNr5LWKGPdCYdS91hDdW/8ENDaKS8YgwXLsA2/iUBw/1+K/2i7pYQoIbive48mO5Hq0mO+DU/QeVXVy5xiUnmR50x6hkwyNX8xOx5i49m/ItiA0OA6Y7W3sXR++6+MMZWQKXiWkfUMHF6faa1ljW62tYz5bQVFfwOO1oPjRH+p1av2xCmRB6xX2Dkwsk="
language: c
compiler: gcc


before_install:
- pip install --user awscli
- docker pull intrigus/docker-raspberry-pi-cross-compiler
- docker run intrigus/docker-raspberry-pi-cross-compiler > ~/bin/rpxc
- chmod +x ~/bin/rpxc
- export PATH=$PATH:$HOME/bin:$HOME/.local/bin
- export RPXC_IMAGE=intrigus/docker-raspberry-pi-cross-compiler

script:
- echo "PKG_CONFIG_DIR=" >> .lwjgl_env_rpxc
- echo "PKG_CONFIG_LIBDIR=${LWJGL_BUILD_SYSROOT}/usr/lib/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/share/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig:${LWJGL_BUILD_SYSROOT}/usr/share/arm-linux-gnueabihf/pkgconfig" >> .lwjgl_env_rpxc
- echo "PKG_CONFIG_SYSROOT_DIR=${LWJGL_BUILD_SYSROOT}" >> .lwjgl_env_rpxc
- echo 'export CC=arm-linux-gnueabihf-gcc;export CXX=arm-linux-gnueabihf-g++;export LD=arm-linux-gnueabihf-ld;export AR=arm-linux-gnueabihf-ar;export AS=arm-linux-gnueabihf-as;export NM=arm-linux-gnueabihf-nm;export STRIP=arm-linux-gnueabihf-strip;export RANLIB=arm-linux-gnueabihf-ranlib;export OBJDUMP=arm-linux-gnueabihf-objdump' >> tempScript.sh
- echo 'CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ./autogen.sh --target=arm-linux-gnueabihf --with-jemalloc-prefix=je_ --enable-lazy-lock --disable-stats --disable-fill' >> tempScript.sh
- echo 'make' >> tempScript.sh
- echo 'cd lib' >> tempScript.sh
- echo 'arm-linux-gnueabihf-strip libjemalloc.so' >> tempScript.sh
- chmod +x tempScript.sh
- rpxc --args "--env-file .lwjgl_env_rpxc" bash -c './tempScript.sh' 
#- "aws s3 cp libjemalloc.so s3://build.lwjgl.org/nightly/linux/x64/libjemalloc.so --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
#- "git log --pretty=format:%H HEAD~2..HEAD~1 | head -n 1 > revision.git"
#- "aws s3 cp revision.git s3://build.lwjgl.org/nightly/linux/x64/libjemalloc.so.git --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
